export const NAMES_DB: Record<string, { first: string[]; last: string[] }> = {
  'USA': {
    first: ["Jamal", "Marcus", "Luka", "Kevin", "LeBron", "Kobe", "Michael", "Stephen", "Giannis", "Nikola", "Jayson", "Zion", "Ja", "Trae", "De'Aaron", "Devin", "Anthony", "Damian", "Donovan", "Kyrie", "Jimmy", "Klay", "Paul", "Russell", "Bradley", "DeMar", "Zach", "LaVine", "Julius", "Joel", "Bam", "Deandre", "Rudy", "Clint", "Pascal", "Domantas", "Myles", "Jarrett", "Kristaps", "Vucevic", "Jonas", "Brook", "Ayton", "Mitchell", "Darius", "Shai", "Tyrese", "Dejounte", "LaMelo", "Cade", "Fred", "CJ", "Brandon", "Terry", "D'Angelo", "Malcolm", "John", "Chris", "Kyle", "Kemba", "Goran", "Mike", "Ricky", "Derrick", "Lonzo", "RJ", "Cole", "Tyler", "Jordan", "Collin", "Dennis", "Jalen", "Jaden", "Isaiah", "Evan", "Scottie", "Franz", "Paolo", "Chet", "Jabari", "Keegan", "Bennedict", "Shaedon", "Dyson", "Jeremy", "Victor", "Scoot", "Ausar", "Amen", "Keyonte", "Walker", "Taylor", "Gradey", "Bilal", "Cason", "Dereck", "Khris", "Andrew", "Mikal"],
    last: ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Curry", "Durant", "Tatum", "Jokic", "Embiid", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson", "Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes", "Price", "Alvarez", "Castillo", "Sanders", "Patel"]
  },
  'ESP': {
    first: ["Pau", "Marc", "Ricky", "Juan Carlos", "Sergio", "Rudy", "Willy", "Juancho", "Alex", "Fernando", "Jorge", "Jose", "Alberto", "Carlos", "David", "Javier", "Daniel", "Pablo", "Alvaro", "Adrian", "Mario", "Diego", "Hugo", "Marcos", "Ivan", "Raul", "Ruben", "Victor", "Hector", "Aaron", "Aitor", "Oscar", "Roberto", "Samuel", "Iker", "Cristian", "Ismael", "Guillermo", "Nicolas", "Martin", "Lucas", "Mateo", "Leo", "Alejandro", "Enrique", "Ignacio", "Gonzalo", "Julio", "Andres", "Miguel", "Rafael", "Tomas", "Luis", "Antonio", "Francisco", "Manuel", "Pedro", "Jesus", "Angel", "Vicente", "Eduardo", "Joaquin", "Emilio", "Julian", "Gabriel", "Felipe", "Matias", "Bastian", "Bruno", "Thiago", "Gael", "Izan", "Rodrigo", "Alonso", "Cesar", "Felix", "Jon", "Unai", "Paco", "Brais", "Joan", "Pol", "Biel", "Jan", "Nil", "Oriol", "Xavi", "Aleix", "Arnau", "Gerard", "Albert", "Ferran", "Sergi", "Ricard", "Ramon", "Gorka", "Koke", "Asier", "Mikel"],
    last: ["Gasol", "Navarro", "Rubio", "Llull", "Fernandez", "Hernangomez", "Abrines", "Reyes", "Calderon", "Garbajosa", "Rodriguez", "Garcia", "Martinez", "Lopez", "Sanchez", "Perez", "Gomez", "Martin", "Jimenez", "Ruiz", "Hernandez", "Diaz", "Moreno", "Alvarez", "Muñoz", "Romero", "Alonso", "Gutierrez", "Torres", "Dominguez", "Vazquez", "Ramos", "Gil", "Ramirez", "Serrano", "Blanco", "Suarez", "Molina", "Morales", "Ortega", "Delgado", "Castro", "Ortiz", "Marin", "Sanz", "Iglesias", "Nuñez", "Medina", "Garrido", "Cortes", "Castillo", "Santos", "Lozano", "Guerrero", "Cano", "Prieto", "Mendez", "Cruz", "Calvo", "Gallego", "Vidal", "Leon", "Marquez", "Herrera", "Peña", "Flores", "Cabrera", "Campos", "Vega", "Diez", "Fuentes", "Carrasco", "Caballero", "Nieto", "Aguilar", "Pascual", "Santana", "Herrero", "Lorenzo", "Montero", "Hidalgo", "Gimenez", "Ibañez", "Ferrer", "Duran", "Santiago", "Benitez", "Vargas", "Mora", "Arias", "Carmona", "Crespo", "Roman", "Pastor", "Soto", "Saez", "Velasco", "Soler"]
  },
  'ARG': {
    first: ["Facundo", "Emanuel", "Luis", "Andres", "Leandro", "Pablo", "Fabricio", "Carlos", "Walter", "Nicolas", "Luca", "Gabriel", "Patricio", "Federico", "Matias", "Hernan", "Maximiliano", "Diego", "Franco", "Agustin", "Gaston", "Ignacio", "Tomas", "Julian", "Ezequiel", "Mariano", "Sebastian", "Lucas", "Santiago", "Joaquin", "Rodrigo", "Emiliano", "Luciano", "Martin", "Guillermo", "Alejandro", "Cristian", "Juan", "Marcelo", "Jorge", "Ruben", "Roberto", "Ricardo", "Eduardo", "Claudio", "Fernando", "Julio", "Oscar", "Victor", "Gustavo"],
    last: ["Ginobili", "Scola", "Nocioni", "Campazzo", "Delfino", "Prigioni", "Oberto", "Laprovittola", "Vildoza", "Deck", "Brussino", "Garino", "Fierro", "Delia", "Caffaro", "Bolmaro", "Redivo", "Gallizzi", "Romano", "Vaulet", "Sanchez", "Gomez", "Perez", "Fernandez", "Rodriguez", "Gonzalez", "Garcia", "Martinez", "Lopez", "Romero", "Diaz", "Torres", "Alvarez", "Ruiz", "Ramirez", "Flores", "Benitez", "Acosta", "Medina", "Herrera", "Aguilar", "Rios", "Rojas", "Gimenez", "Peralta", "Castro", "Silva", "Quiroga", "Navarro"]
  },
  'LTU': {
    first: ["Arvydas", "Domantas", "Sarunas", "Jonas", "Mindaugas", "Linas", "Mantas", "Rokas", "Tomas", "Ignas", "Lukas", "Paulius", "Arturas", "Donatas", "Edgaras", "Eimantas", "Gytis", "Martynas", "Tadas", "Vytautas", "Darius", "Gintaras", "Kestutis", "Vaidas", "Zydrunas", "Antanas", "Dainius", "Egidiijus", "Klaidas", "Rimas", "Simas", "Vidas", "Aidas", "Gvidas", "Ovidijus", "Rimantas", "Stepas", "Valdas", "Andrius", "Deividas", "Evaldas", "Gediminas", "Justas", "Karolis", "Laurynas", "Nerijus", "Osvaldas", "Ramunas", "Saulius", "Vilius"],
    last: ["Sabonis", "Valanciunas", "Jasikevicius", "Macijauskas", "Kleiza", "Ilgauskas", "Motiejunas", "Jokubaitis", "Kuzminskas", "Seibutis", "Grigonis", "Gudaitis", "Ulanovas", "Kalnietis", "Brazdeikis", "Kavaliauskas", "Giedraitis", "Dimsa", "Butkevicius", "Masiulis", "Echodas", "Sirvydis", "Tubelis", "Sedekerskis", "Kulboka", "Jankunas", "Maciulis", "Pocius", "Lavrinovic", "Songaila", "Kaukenas", "Kurtinaitis", "Siskauskas", "Stombergas", "Zukauskas", "Timinskas", "Einikis", "Karnisovas", "Praskevicius", "Marciulionis", "Chomicius", "Jovaisa", "Paulauskas", "Urbonas", "Petrauskas", "Kazlauskas", "Stankevicius", "Navickas", "Zilinskas"]
  },
  'SVK': {
    first: ["Marek", "Martin", "Peter", "Juraj", "Tomas", "Milan", "Michal", "Jozef", "Lukas", "Andrej", "Jakub", "Matej", "Filip", "Patrik", "Samuel", "Jan", "Stefan", "Ivan", "Pavol", "Vladimir", "David", "Richard", "Radoslav", "Igor", "Robert", "Lubomir", "Marian", "Miroslav", "Anton", "Frantisek", "Dominik", "Simon", "Adam", "Daniel", "Oliver", "Kristian", "Branislav", "Julius", "Ondrej", "Zdeno", "Boris", "Rastislav", "Vojtech", "Eduard", "Kamil", "Jaroslav", "Gabriel", "Viliam", "Denis", "Alex"],
    last: ["Vesely", "Hamsik", "Skriniar", "Lobotka", "Kucka", "Dubravka", "Pekarik", "Mak", "Weiss", "Duda", "Bozenik", "Hancko", "Vavro", "Suslov", "Hrosovsky", "Bero", "Schranz", "Gyomber", "Valjent", "Tomic", "Rusnak", "Kovár", "Ravas", "Sulla", "Gajanec", "Nemec", "Polak", "Kovac", "Balaz", "Varga", "Gallo", "Mraz", "Horvath", "Sykora", "Urban", "Gajdos", "Ondrus", "Farkas", "Kollar", "Sloboda", "Chovan", "Toth", "Sabo", "Krajcir", "Molnar", "Beno", "Halak", "Chara", "Gaborik", "Hossa"]
  },
  'CHN': {
    first: ["Yao", "Jianlian", "Jeremy", "Yi", "Zhou", "Guo", "Wang", "Mengke", "Sun", "Ding", "Zhao", "Zhelin", "Abudushalamu", "Rui", "Hao", "Wei", "Lei", "Jian", "Peng", "Bin", "Bo", "Chao", "Chen", "Cheng", "Da", "Dong", "Fan", "Feng", "Gang", "Hai", "He", "Heng", "Hong", "Hui", "Jia", "Jie", "Jin", "Jing", "Jun", "Kai", "Kang", "Ke", "Kun", "Li", "Liang", "Lin", "Ling", "Long", "Lu", "Min"],
    last: ["Ming", "Lin", "Qi", "Ailun", "Zhizhi", "Bateer", "Yue", "Yuhang", "Rui", "Hao", "Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao", "Wu", "Zhou", "Xu", "Sun", "Ma", "Zhu", "Hu", "Guo", "He", "Gao", "Luo", "Zheng", "Liang", "Xie", "Song", "Tang", "Han", "Feng", "Deng", "Cao", "Peng", "Zeng", "Xiao", "Tian", "Dong", "Yuan", "Pan", "Yu", "Jiang", "Cai"]
  },
  'FRA': {
    first: ["Tony", "Rudy", "Nicolas", "Evan", "Victor", "Boris", "Nando", "Frank", "Guerschon", "Theo", "Kilian", "Sekou", "Elie", "Timothe", "Ousmane", "Tidjane", "Bilal", "Zaccharie", "Rayan", "Alexandre", "Leo", "Hugo", "Mathis", "Arthur", "Louis", "Jules", "Gabriel", "Enzo", "Maxime", "Antoine", "Clement", "Nathan", "Baptiste", "Gabin", "Tom", "Paul", "Pierre", "Jean", "Francois", "Jacques", "Michel", "Claude", "Philippe", "Alain", "Bernard", "Thierry", "Laurent", "Olivier", "Stephane", "Vincent"],
    last: ["Parker", "Gobert", "Batum", "Fournier", "Wembanyama", "Diaw", "De Colo", "Ntilikina", "Yabusele", "Maledon", "Hayes", "Doumbouya", "Okobo", "Luwawu", "Dieng", "Salaun", "Coulibaly", "Risacher", "Rupert", "Sarr", "Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard", "Petit", "Durand", "Leroy", "Moreau", "Simon", "Laurent", "Lefevre", "Michel", "Garcia", "David", "Bertrand", "Roux", "Vincent", "Morel", "Girard", "Andre", "Mercier", "Dupont", "Lambert", "Bonnet", "Francois", "Martinez"]
  },
  'GER': {
    first: ["Dirk", "Dennis", "Franz", "Moritz", "Maxi", "Daniel", "Johannes", "Isaac", "Paul", "Maodo", "Andreas", "Niels", "Christian", "Robin", "Philipp", "Lukas", "Leon", "Maximilian", "Felix", "Tim", "Jonas", "Julian", "Florian", "Alexander", "David", "Jan", "Simon", "Tobias", "Michael", "Thomas", "Markus", "Stefan", "Matthias", "Martin", "Sebastian", "Frank", "Jens", "Uwe", "Jorg", "Klaus", "Bernd", "Jurgen", "Ralf", "Dieter", "Wolfgang", "Peter", "Hans", "Karl"],
    last: ["Nowitzki", "Schroder", "Wagner", "Kleber", "Theis", "Voigtmann", "Bonga", "Zipser", "Lo", "Hartenstein", "Obst", "Giffey", "Thiemann", "Bartzky", "Pleiss", "Muller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Becker", "Schulz", "Hoffmann", "Schafer", "Koch", "Bauer", "Richter", "Klein", "Wolf", "Neumann", "Schwarz", "Zimmermann", "Braun", "Kruger", "Hofmann", "Hartmann", "Lange", "Schmitt", "Werner", "Krause", "Meier", "Lehmann", "Schmid", "Schulze", "Maier", "Kohler", "Herrmann"]
  }
};
